# .azure-devops/templates/deploy-jobs.yml
parameters:
  environment: ''

jobs:
- job: Deploy_k8s
  displayName: Deploy to Kubernetes
  pool:
    name: 'MySelfHostedAgentPool'  # Changed from vmImage: 'ubuntu-latest'
  steps:
  - task: KubernetesManifest@0
    displayName: Deploy manifests
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: $(kubernetesServiceConnection)
      namespace: 'eventflex-${{ parameters.environment }}'
      manifests: |
        k8s/**/*.yaml
      containers: |
        $(containerRegistry)/eventflex-web:$(Build.BuildId)
        $(containerRegistry)/messaging-service:$(Build.BuildId)
        $(containerRegistry)/notification-service:$(Build.BuildId)
        $(containerRegistry)/event-type-management-api:$(Build.BuildId)
        $(containerRegistry)/user-management-api:$(Build.BuildId)