apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: eventflex.azurecr.io/notification-service:$(Build.BuildId)
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        env:
        - name: KAFKA_CLIENT_ID
          value: "notification-service"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_GROUP_ID
          value: "notification-group"
        - name: PORT
          value: "3003"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: username
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m" 