apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
type: Opaque
data:
  # Replace these with base64 encoded values of your actual credentials
  username: BASE64_ENCODED_USERNAME
  password: BASE64_ENCODED_PASSWORD 