apiVersion: v1
kind: Service
metadata:
  name: eventflex-web
  namespace: event-flex
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
spec:
  type: NodePort
  selector:
    app: eventflex-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000  # a port in the range 30000-32767