services:

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: EventFlex.UserManagement
      POSTGRES_USER: billy
      POSTGRES_PASSWORD: qazwsx1@3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - my_network

  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: UserManagement.API/Dockerfile
      args:
        PROJECT_PATH: UserManagement.API/UserManagement.API.csproj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=EventFlex.UserManagement;Username=billy;Password=qazwsx1@3
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - my_network

volumes:
  postgres-data:
 
networks:
  my_network:
    driver: bridge
