apiVersion: v1
kind: Namespace
metadata:
  name: event-flex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: event-flex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "EventFlex.UserManagement"
        - name: POSTGRES_USER
          value: "billy"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: event-flex
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432