apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # Replace with base64 encoded connection string, example connection string:
  # Host=postgres;Port=5432;Database=EventFlex.UserManagement;Username=billy;Password=your_password
  connection-string: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9RXZlbnRGbGV4LlVzZXJNYW5hZ2VtZW50O1VzZXJuYW1lPWJpbGx5O1Bhc3N3b3JkPXFhendzeDFAMw== 