version: '3.8'

services:
  web:
    image: billyjiang/eventflex-web:latest
    container_name: eventflex-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://usermanagementapi:8080/api
      - NEXT_PUBLIC_API_URL_EVENTTYPE=https://event-type-management.azurewebsites.net/api
    volumes:
      # 将宿主机上的证书目录挂载到容器内的/app/certs
      - /home/ubuntu/certs:/app/certs
      # - ./eventflex-web:/app
    command: npm run dev -- --experimental-https --turbopack
    networks:
      - my_network

networks:
  my_network:
    external: true