version: '3.8'

services:
  web:
    image: billyjiang/eventflex-web:latest
    container_name: eventflex-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://usermanagementapi:8080/api
    networks:
      - my_network

networks:
  my_network:
    external: true