@UserManagement.API_HostAddress = http://localhost:5099

GET {{UserManagement.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{UserManagement.API_HostAddress}}/api/people
Accept: application/json

###

POST {{UserManagement.API_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "username": "admin@gmail.com",
  "password": "Admin@123"
}

###