name: Messaging Service CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'MessagingService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'MessagingService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: |
          cd MessagingService
          npm install

      # Run tests
      # - name: Run tests
      #   run: |
      #     cd MessagingService
      #     npm run test:ci

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          cd MessagingService
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest --push .

      # Copy docker-compose.yml to EC2
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE }}
          username: ${{ secrets.AWS_UBUNTU_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          source: "./MessagingService/docker/docker-compose.yml"
          target: "/home/${{ secrets.AWS_UBUNTU_USER }}"

      # Deploy to AWS EC2
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE }}
          username: ${{ secrets.AWS_UBUNTU_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            echo "SSH connection successful"

            echo ${{ secrets.DOCKER_USERNAME }}

            # Update the package index
            sudo apt-get update -y

            # Initialize the variable
            docker_needs_restart=false

            # Check if Docker is installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get install docker -y
              sudo systemctl start docker
              sudo systemctl enable docker
              docker_needs_restart=true
            fi

            # Create docker group if it doesn't exist
            if ! getent group docker > /dev/null; then
              sudo groupadd docker
              docker_needs_restart=true
            fi

            # Add user to docker group
            sudo usermod -aG docker ${{ secrets.AWS_UBUNTU_USER }}

            # Check if Docker Compose is installed
            if command -v docker-compose &> /dev/null; then
              echo "Docker Compose is already installed"
              docker-compose --version
            else
              echo "Docker Compose is not installed, installing now"
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
              docker-compose --version
              docker_needs_restart=true
            fi

            # Install nc (netcat)
            if ! command -v nc &> /dev/null; then
              sudo apt-get install -y nmap-ncat
            fi

            # Install missing Python libraries
            sudo apt-get install -y python3 python3-pip
            sudo pip3 install cryptography

            # Restart Docker only if necessary
            if [ "$docker_needs_restart" = true ]; then
              sudo systemctl restart docker
            fi

            # Pull the Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest

            # List containers before stopping
            echo "Containers before stopping:"
            sudo docker ps -a

            # Stop and remove existing containers
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^messaging-service\$"; then
              sudo docker stop messaging-service
              sudo docker rm messaging-service
            fi

            # List containers after stopping
            echo "Containers after stopping:"
            sudo docker ps -a

            # Remove unused Docker images
            sudo docker image prune -f

            # Change directory to home/ec2-user/MessagingService/docker
            cd /home/${{ secrets.AWS_UBUNTU_USER }}/MessagingService/docker
            # Run Zookeeper and Kafka containers using docker-compose
            sudo -E VAR_DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker-compose -f docker-compose.yml up -d zookeeper kafka
            for i in {1..10}; do
              if echo srvr | nc localhost 2181; then
                echo "Zookeeper is ready!"
                break
              fi
              sleep 5
            done
            for i in {1..10}; do
              if docker exec kafka kafka-topics --bootstrap-server kafka:9092 --list; then
                echo "Kafka is ready!"
                break
              fi
              sleep 5
            done

            # Wait 60s for Kafka
            sleep 60

            # Run the application container using docker-compose
            sudo docker-compose -f docker-compose.yml up -d messaging-service
            # Check if the container is running
            if [ $(sudo docker inspect -f '{{.State.Running}}' messaging-service) != "true" ]; then
              echo "messaging-service container failed to start. Logs:"
              sudo docker logs messaging-service
              exit 1
            fi
          debug: true  # Enable debug mode