name: Build and Deploy NotificationService

on:
  push:
    branches:
      - main
    paths:
      - 'NotificationService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'NotificationService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd NotificationService
          npm install

      - name: Build the project
        run: |
          cd NotificationService
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd NotificationService
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_KEY }}

      # - name: Copy .env file to EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE }}
      #     username: ${{ secrets.AWS_UBUNTU_USER }}
      #     key: ${{ secrets.AWS_EC2_KEY }}
      #     source: "NotificationService/.env"
      #     target: "/home/${{ secrets.AWS_UBUNTU_USER }}"

      - name: Install Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE }}
          username: ${{ secrets.AWS_UBUNTU_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            echo "SSH connection successful"

            # Update the package index
            sudo apt-get update -y

            # Check if Docker is installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get install docker -y
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Create docker group if it doesn't exist
            if ! getent group docker > /dev/null; then
              sudo groupadd docker
              docker_needs_restart=true
            fi

            # Add user to docker group
            sudo usermod -aG docker ${{ secrets.AWS_UBUNTU_USER }}

      - name: Deploy Docker container to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE }}
          username: ${{ secrets.AWS_UBUNTU_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

            # Stop and remove existing containers
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^notification-service\$"; then
              sudo docker stop notification-service
              sudo docker rm notification-service
            fi

            docker run -d -p 3003:3003 --name notification-service --network my_network ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
          debug: true  # Enable debug mode

