name: Build and Deploy NotificationService

on:
  push:
    branches:
      - main
    paths:
      - 'NotificationService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'NotificationService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd NotificationService
          npm install

      - name: Build the project
        run: |
          cd NotificationService
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd NotificationService
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_KEY }}

      # - name: Copy .env file to EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE_PRIVATE_DNS }}
      #     username: ${{ secrets.AWS_EC2_USER }}
      #     key: ${{ secrets.AWS_EC2_KEY }}
      #     source: "NotificationService/.env"
      #     target: "/home/${{ secrets.AWS_EC2_USER }}"

      - name: Install Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE_PRIVATE_DNS }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            sudo yum update -y
            sudo amazon-linux-extras install docker -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ${{ secrets.AWS_EC2_USER }}

      - name: Deploy Docker container to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_MESSAGING_SERVICE_PRIVATE_DNS }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
            docker stop notification-service || true
            docker rm notification-service || true
            docker run -d -p 3000:3000 --name notification-service --network my_network ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
          debug: true  # Enable debug mode

